---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r readData, echo=TRUE}
activityData <- read.csv("activity.csv", header=TRUE, na.strings="NA")
str(activityData)
```

## What is mean total number of steps taken per day?

```{r stepsByDay, echo=TRUE}
library("sqldf")
sums <- sqldf("select sum(steps) sums from activityData where steps is not null group by date")
mean(sums$sums)
```

## What is the average daily activity pattern?

```{r stepsByInterval, echo=TRUE}
# aggregate data by interval and find ave for each interval
asteps <- sqldf("select interval, avg(steps) aveSteps from activityData where steps is not null group by interval")
# make a plot of the summary
plot(asteps$interval, asteps$aveSteps, type="l", main="Average steps in a day by 5 min intervals")
# find max activity interval
sqldf("select interval, max(aveSteps) from asteps")
```

## Imputing missing values

```{r imputation, echo=TRUE}
# Calculate and report the total number of missing values in the dataset (i.e. the total number of rows with NAs):
sqldf("select count(interval) from activityData where steps is null")
# replace NA values with the ave for the time interval
adImputed <- sqldf("select round(asteps.aveSteps) 'steps', activityData.date 'date', activityData.interval 'interval' from activityData, asteps where activityData.steps is null and activityData.interval = asteps.interval union select steps, date, interval from activityData where steps is not null")
# Make a histogram of the total number of steps taken each day
sumsImputed <- sqldf("select sum(steps) sums from adImputed group by date")
hist(sumsImputed$sums)
# mean and median of imputed dataset
mean(sumsImputed$sums)
median(sumsImputed$sums)
# mean and median of original data
mean(sums$sums)
median(sums$sums)

# the diff in means is (%):
abs(mean(sumsImputed$sums) - mean(sums$sums)) * 100 / mean(sums$sums)
```

## Are there differences in activity patterns between weekdays and weekends?

```{r weekPattern, echo=TRUE}
# Create a new factor variable in the dataset with two levels – “weekday” and “weekend” indicating whether a given date is a weekday or weekend day.
adImputed$daysOfWeek <- weekdays(strptime(adImputed$date, "%Y-%m-%d"), abbreviate = FALSE)
adImputed$weekdays <- rep('weekday', length(adImputed$date))
adImputed$weekdays[adImputed$daysOfWeek=="Sunday"] <- 'weekend'
adImputed$weekdays[adImputed$daysOfWeek=="Saturday"] <- 'weekend'
adImputed$weekdays <- as.factor(adImputed$weekdays)
# Make a plot containing a time series plot of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all weekday days or weekend days (y-axis)

awSteps <- sqldf("select interval, avg(steps) aveSteps, weekdays from adImputed group by interval, weekdays")

library("ggplot2")
qplot(interval, aveSteps, data=awSteps, facets=. ~ weekdays, geom=c("line"), main="Average activity patterns on weekdays vs weekends")
```

